version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    entrypoint: [ "/app/start.sh" ]
    command: [ "/app/main" ]
