// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"context"
)

type Querier interface {
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error)
	CreateTransfer(ctx context.Context, arg CreateTransferParams) (Transfer, error)
	DeleteAccount(ctx context.Context, id int64) error
	DeleteEntry(ctx context.Context, id int64) (int64, error)
	DeleteTransfer(ctx context.Context, id int64) (int64, error)
	GetAccount(ctx context.Context, id int64) (Account, error)
	GetEntry(ctx context.Context, arg GetEntryParams) ([]Entry, error)
	GetTransfer(ctx context.Context, arg GetTransferParams) ([]Transfer, error)
	ListAccounts(ctx context.Context, arg ListAccountsParams) ([]Account, error)
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
