apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - groups:
      - system:masters
      userarn: ${{ secrets.KUBE_USER_ARN }}
      username: github_cd
