apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-api-deployment
  namespace: default
  labels:
    app: bank-api-deployment
spec:
  selector:
    matchLabels:
      app: bank-api-deployment
  replicas: 2
  template:
    metadata:
      labels:
        app: bank-api-deployment
    spec:
      containers:
        - name: bank-api-deployment
          image: ${{ secrets.SECRETS_NAME }}/${{ secrets.REPO_NAME }}:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 8080
      restartPolicy: Always
