apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: aymanabdelrhman12@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: bank-issuer-account-key
    solvers:
    - http01:
        ingress:
          class: nginx